# Default Helm values for Virtual Kubelet NERSC provider

replicaCount: 1

image:
  repository: registry.example.com/vk-provider-nersc
  tag: latest
  pullPolicy: IfNotPresent

sfApiEndpoint: "https://api.nersc.gov/api/v1.2"
sfApiToken: "" # Will be stored in secret

vkNodeName: "perlmutter-vk"

serviceAccount:
  name: vk-nersc

rbac:
  create: true

resources: {}
nodeSelector:
  kubernetes.io/os: linux

tolerations: []
affinity: {}

extraEnv: []

# StatefulSet support
statefulset:
  enabled: false
  name: hpc-stateful
  replicas: 2
  project: m1234
  inputSource: "globus://endpoint-id/path/to/data"
  outputDest: "globus://endpoint-id/path/to/output"
  stageOut: "true"
  nodeSelector: perlmutter-vk
  container:
    name: compute
    image: registry.example.com/compute:latest
    command: ["python"]
    args: ["compute.py"]
  volumeMounts:
    - name: data
      mountPath: /mnt/data
      readOnly: false
  volumes:
    - name: data
      claimName: hpc-data-pvc
